### ISSUE TITLE
Bug in merge?

### ISSUE THREAD

**Issue by Javerlarb** [snayfach/IGGsearch#31]
I am able to complete run_iggsearch.py search successfully and opening the individual species_profile.tsv for my samples looks great, but for some reason I can't get them all to merge without getting this error:

```
run_iggsearch.py merge --input iggsearch  --intype dir --outdir .
## Listing input
  6 total samples
  module: 0.0 seconds, program: 0.0 seconds, peak RAM: 0.03 GB

## Reading data
  module: 0.0 seconds, program: 0.0 seconds, peak RAM: 0.04 GB

## Writing matrix files
Traceback (most recent call last):
  File "/media/julio/Storage1/Software/IGGsearch/run_iggsearch.py", line 34, in <module>
    merge.main()
  File "/media/julio/Storage1/Software/IGGsearch/iggsearch/merge.py", line 150, in main
    value = str(data[sample][species][field])
KeyError: 'species_presence'

```
I have used the merge function on MIDAS before and imagine this is similar. I have also tried inputting as list and text file, but I am getting the same error. I used:
Python = 3.6.7
numpy =1.15.0
pysam = 0.15.0
Bowtie2 = 2.3.5
samtools = 1.9

**Comment by snayfach** [comment]
Thanks for the bug report. I found and fixed the problem but have not yet tested it. If the error persists, please let me know.

**Comment by Javerlarb** [comment]
Thanks for the quick fix. All seems to be working well, no errors now. Although the merged table is returning OTU IDs, I'm not sure if it should be the species name? I've attached it for reference.
[total_mapped_reads.txt](https://github.com/snayfach/IGGsearch/files/3518071/total_mapped_reads.txt)

**Comment by snayfach** [comment]
OTU ids are correct. There should be a database file with metadata on all the OTU ids, including species names. Please let me know if you find any other issues.
